apiVersion: batch/v1
kind: CronJob
metadata:
  name: a6j2-1-downloader-cronjob
  namespace: radiko
spec:
  schedule: "0 14 * * 1-5" # Every weekday at 23:00 JST
  startingDeadlineSeconds: 900
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: a6j2-1-radiko-downloader
            image: us-west1-docker.pkg.dev/takedarut-radiko-downloader/radiko-downloader/radiko-downloader@sha256:5c4d6f088e1e75d6b298b3b11ea8d4f977695cacb1d56bb55346e4162e5ec4b9
            env:
              - name: PROGRAM_START_TIME
                value: "20:00"
              - name: RADIO_STATION
                value: "TBS"
              - name: FILE_NAME_PREFIX
                value: "a6j2"
              - name: PROGRAM_TITLE
                value: "アフター６ジャンクション２"
              - name: RCLONE_DRIVE_ROOT_FOLDER_ID
                valueFrom:
                  secretKeyRef:
                    name: google-drive-folder-secrets
                    key: A6J2_FOLDER
          imagePullSecrets:
            - name: artifact-registry-secret
          restartPolicy: Never
