apiVersion: batch/v1
kind: CronJob
metadata:
  name: a6j2-2-downloader-cronjob
  namespace: radiko
spec:
  schedule: "0 23 * * 1-5" # Every weekday at 23:00 
  startingDeadlineSeconds: 900
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: a6j2-2-radiko-downloader
            image: us-west1-docker.pkg.dev/takedarut-radiko-downloader/radiko-downloader/radiko-downloader@sha256:2ac8961b90f2edf6d591b09362632055f2c73e110057118aca695e3478123f27
            env:
              - name: PROGRAM_START_TIME
                value: "21:00"
              - name: RADIO_STATION
                value: "TBS"
              - name: FILE_NAME_PREFIX
                value: "a6j2"
              - name: RCLONE_DRIVE_ROOT_FOLDER_ID
                valueFrom:
                  secretKeyRef:
                    name: google-drive-folder-secrets
                    key: A6J2_FOLDER
          imagePullSecrets:
            - name: artifact-registry-secret
          restartPolicy: Never

