apiVersion: batch/v1
kind: CronJob
metadata:
  name: a6j2-2-downloader-cronjob
  namespace: radiko
spec:
  schedule: "0 14 * * 1-5" # Every weekday at 23:00 JST
  startingDeadlineSeconds: 900
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: a6j2-2-radiko-downloader
            image: us-west1-docker.pkg.dev/takedarut-radiko-downloader/radiko-downloader/radiko-downloader@sha256:a89927404fdbf31db9de9459b0da17482f7bc62b7fe561f01560acb321a782e6
            env:
              - name: PROGRAM_START_TIME
                value: "21:00"
              - name: RADIO_STATION
                value: "TBS"
              - name: FILE_NAME_PREFIX
                value: "a6j2"
              - name: PROGRAM_TITLE
                value: "アフター６ジャンクション２"
              - name: RCLONE_DRIVE_ROOT_FOLDER_ID
                valueFrom:
                  secretKeyRef:
                    name: google-drive-folder-secrets
                    key: A6J2_FOLDER
          imagePullSecrets:
            - name: artifact-registry-secret
          restartPolicy: Never

