apiVersion: batch/v1
kind: CronJob
metadata:
  name: a6j2-2-downloader-cronjob
  namespace: radiko
spec:
  schedule: "0 14 * * 1-4" # Every weekday at 23:00 JST
  startingDeadlineSeconds: 900
  suspend: false
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 604800
      template:
        spec:
          containers:
          - name: a6j2-2-radiko-downloader
            image: us-west1-docker.pkg.dev/takedarut-radiko-downloader/radiko-downloader/radiko-downloader@sha256:0b2bd5eb6b4eb87e29317aaf9c1b109db868f53b2dd48fce8ecfb3c97b2fe16b
            env:
              - name: AREA_ID
                value: "JP13" # Tokyo
              - name: PROGRAM_START_TIME
                value: "21:00"
              - name: RADIO_STATION
                value: "TBS"
              - name: FILE_NAME_PREFIX
                value: "a6j2"
              - name: PROGRAM_TITLE
                value: "アフター６ジャンクション２"
              - name: PROGRAM_DURATION_MIN
                value: "60"
              - name: GDRIVE_FOLDER_ID
                valueFrom:
                  secretKeyRef:
                    name: google-drive-folder-secrets
                    key: A6J2_FOLDER
          imagePullSecrets:
            - name: artifact-registry-secret
          restartPolicy: Never

