apiVersion: batch/v1
kind: CronJob
metadata:
  name: as1422-downloader-cronjob
  namespace: radiko
spec:
  schedule: "0 16 * * 0" # Every Monday at 1:00 AM JST
  startingDeadlineSeconds: 900
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: as1422-radiko-downloader
            image: us-west1-docker.pkg.dev/takedarut-radiko-downloader/radiko-downloader/radiko-downloader@sha256:06d7215d5a05afe07fd38c4fd116febc6ada29a29528e38744e24817cfb95cba
            env:
              - name: PROGRAM_START_TIME
                value: "00:00"
              - name: RADIO_STATION
                value: "JORF"
              - name: FILE_NAME_PREFIX
                value: "as1422"
              - name: PROGRAM_TITLE
                value: "アンジュルムステーション1422"
              - name: RCLONE_DRIVE_ROOT_FOLDER_ID
                valueFrom:
                  secretKeyRef:
                    name: google-drive-folder-secrets
                    key: AS1422_FOLDER
          imagePullSecrets:
            - name: artifact-registry-secret
          restartPolicy: Never
