apiVersion: batch/v1
kind: CronJob
metadata:
  name: as1422-downloader-cronjob
  namespace: radiko
spec:
  schedule: "0 1 * * 1"
  startingDeadlineSeconds: 900
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: as1422-radiko-downloader
            image: us-west1-docker.pkg.dev/takedarut-radiko-downloader/radiko-downloader/radiko-downloader@sha256:39722043d01bb1609f58d7a83b382d4d7acf76ac98377d7b734772f1077e0bad
            env:
              - name: PROGRAM_START_TIME
                value: "00:00"
              - name: RADIO_STATION
                value: "JORF"
              - name: RCLONE_DRIVE_ROOT_FOLDER_ID
                valueFrom:
                  secretKeyRef:
                    name: google-drive-folder-secrets
                    key: AS1422_FOLDER
          imagePullSecrets:
            - name: artifact-registry-secret
          restartPolicy: Never
