apiVersion: batch/v1
kind: CronJob
metadata:
  name: radiko-downloader-cronjob
spec:
  schedule: "0 1 * * 1"
  startingDeadlineSeconds: 900
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: as1422-radiko-downloader
            image: us-west1-docker.pkg.dev/takedarut-radiko-downloader/radiko-downloader/radiko-downloader@sha256:5a8c5d55fad063ed86ea240dd3b19122e47a09d65b971eb82462d2f584207b3a
            env:
              - name: PROGRAM_START_TIME
                value: "00:00"
              - name: RADIO_STATION
                value: "JORF"
          imagePullSecrets:
            - name: artifact-registry-secret
          restartPolicy: Never
