apiVersion: batch/v1
kind: CronJob
metadata:
  name: radiko-downloader-cronjob
spec:
  schedule: "0 1 * * 1"
  startingDeadlineSeconds: 900
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: as1422-radiko-downloader
            image: us-west1-docker.pkg.dev/takedarut-radiko-downloader/radiko-downloader/radiko-downloader@sha256:3469abe1139491c5b8b03874b161949494ff299f89e813928e2483ac88184891
            env:
              - name: PROGRAM_START_TIME
                value: "00:00"
          imagePullSecrets:
            - name: artifact-registry-secret
          restartPolicy: Never
