apiVersion: batch/v1
kind: CronJob
metadata:
  name: as1422-downloader-cronjob
  namespace: radiko
spec:
  schedule: "45 15 * * 0" # Every Monday at 0:45 AM JST
  startingDeadlineSeconds: 900
  suspend: false
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 604800
      template:
        spec:
          containers:
          - name: as1422-radiko-downloader
            image: us-west1-docker.pkg.dev/takedarut-radiko-downloader/radiko-downloader/radiko-downloader@sha256:bfeda937f41d673a605228dcb1674c16909810b448299ee2fec2f1fbadae739e
            env:
              - name: AREA_ID
                value: "JP13" # Tokyo
              - name: PROGRAM_START_TIME
                value: "00:00"
              - name: RADIO_STATION
                value: "JORF"
              - name: FILE_NAME_PREFIX
                value: "as1422"
              - name: PROGRAM_TITLE
                value: "アンジュルムステーション1422"
              - name: PROGRAM_DURATION_MIN
                value: "30"
              - name: GDRIVE_FOLDER_ID
                valueFrom:
                  secretKeyRef:
                    name: google-drive-folder-secrets
                    key: AS1422_FOLDER
          imagePullSecrets:
            - name: artifact-registry-secret
          restartPolicy: Never
